# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
lang: cn
languages: ["en", "cn"]
title: "Rowl1ng|黑客与画家"
email: "ling.rowling.luo@gmail.com"
description: "Tech & Art"
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://rowl1ng.com/blog" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "Rowl1ng"
github_username:  "Rowl1ng"
signoff:          "Rowl1ng" # Your name
google_analytics: UA-71226909-1
share:            true
# 分页
paginate: 15
paginate_path: "page:num"
# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-paginate
#  - jekyll-feed


links:
  - name:         TECH
    url:          /blog/tech
    external:     false
  - name:         ART
    url:          /blog/art
    external:     false
  - name:         BOOK
    url:          /blog/book
    external:     false
  - name:         WRITE
    url:          /blog/write
    external:     false
  - name:         WIKI
    url:          /mybook
    external:     false
  - name:         FISH
    url:          /NeuralFish
    external:     false
  - name:         ARCHIVE
    url:          /archives
    external:     false
  - name:         TAGS
    url:          /tags
    external:     false
  - name:         ABOUT
    url:          /about
    external:     false

permalink: /:categories/:title.html
defaults:
  - values:
      layout: "default"
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
