auto: true

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
pygments: true
paginate: 8
permalink: /:title
excerpt_separator: "<!-- more -->"
title: Rowl1ng.com
url: http://rowl1ng.com
feed: /atom.xml
author_info: <a href="http://rowl1ng.com/">Rowl1ng</a>
