url: http://rowl1ng.com

watch: true

markdown: Pandoc
pandoc:
  extensions:
    - normalize
    - smart
    - mathjax
    - csl: _styles/apa.csl
#    - bibliography: bibliography/references.bib

jekyll-archives:
  enabled: []
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

highlighter: rouge
paginate: 8
permalink: /:title
excerpt_separator: "<!-- more -->"
title: Rowl1ng.com
author_info: <a href="http://rowl1ng.com/">Rowl1ng</a>
